### PR TITLE
Clean up and update to ibm-fhir-server 4.7.0

### LINKED ISSUE #1: Password
Hello there,

I cloned the Git repo but inside I find a lot of "change-password" values which are not being documented.

Should they be changed or not?!

### PR DESCRIPTION
**Pull request by makuser**
- Fixes #1 
- Updates config format to Liberty server configDropins as per https://github.com/IBM/FHIR/releases#460-migration-considerations
- Uses `ibmcom/ibm-fhir-schematool` for schema init and updates
- `change-password` split up, to distinguish passwords easily: `fhirserver:change-postgres-password` (DB server), `fhiruser:change-user-password`, `fhiradmin:change-admin-password`
- Update `ibmcom/ibm-fhir-server` to 4.7.0

### CODE REVIEW

**Comment by ayselafsar** [comment]
Thanks for this PR. Looks good to me, i just need to test it before merge.

**Comment by derritter88** [comment]
any progress on that? 
I really would like to test it.

**Review by ayselafsar — CHANGES_REQUESTED** [review]
Sorry for the delay testing this PR.

@makuser I get the following exception when trying to get data from the FHIR server running with the changes in this PR. Looks like data schema was not deployed and database was not initialized.

```
2021-06-28T19:51:00.796285000Z Caused by: org.postgresql.util.PSQLException: ERROR: schema "fhirdata" does not exist
2021-06-28T19:51:00.796288256Z   Position: 15
2021-06-28T19:51:00.796299501Z 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
2021-06-28T19:51:00.796304187Z 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
2021-06-28T19:51:00.796311038Z 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
2021-06-28T19:51:00.796320006Z 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
2021-06-28T19:51:00.796324060Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
2021-06-28T19:51:00.796337486Z 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
2021-06-28T19:51:00.796346399Z 	at org.postgresql.jdbc.PgCallableStatement.executeWithFlags(PgCallableStatement.java:83)
2021-06-28T19:51:00.796351710Z 	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
2021-06-28T19:51:00.796356391Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-06-28T19:51:00.796361837Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-06-28T19:51:00.796366385Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-06-28T19:51:00.796371467Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-06-28T19:51:00.796375392Z 	at org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:441)
2021-06-28T19:51:00.796631486Z 	at com.sun.proxy.$Proxy78.execute(Unknown Source)
2021-06-28T19:51:00.796645981Z 	at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.execute(WSJdbcPreparedStatement.java:395)
2021-06-28T19:51:00.796650086Z 	at com.ibm.fhir.persistence.jdbc.postgres.PostgresParameterNamesDAO.readOrAddParameterNameId(PostgresParameterNamesDAO.java:52)
2021-06-28T19:51:00.796653281Z 	... 69 more
2021-06-28T19:51:00.796657323Z 
```

**Comment by makuser** [comment]
> @makuser I get the following exception when trying to get data from the FHIR server running with the changes in this PR. Looks like data schema was not deployed and database was not initialized.

I can not reproduce this. What the content of your docker-compose.yaml?

**Comment by makuser** [comment]
Actually, I probably know what happened on your side. When you start up postgres for the first time, it will take a bit longer and in this case the fhir-schematool will fail to run, but not retry anymore, due to the restart policy 'no'. I now changed that to 'on-failure', so that docker will automatically restart the schematool container, until it quits without an error.

Example when having a specifically delayed postgres db start will work fine now:
```log
The tool behavior being executed is onboard
run.sh - [INFO]: 2021-10-25_13:55:24 - Starting the onboard behavior
run.sh - [INFO]: 2021-10-25_13:55:24 - Activating Network Path Connection...
run.sh - [INFO]: 2021-10-25_13:55:24 - [NETWORK_PATH_CHECK] - FAILURE - Unable to connect to database - postgres:5432
The tool behavior being executed is onboard
run.sh - [INFO]: 2021-10-25_13:55:25 - Starting the onboard behavior
run.sh - [INFO]: 2021-10-25_13:55:25 - Activating Network Path Connection...
run.sh - [INFO]: 2021-10-25_13:55:25 - [NETWORK_PATH_CHECK] - FAILURE - Unable to connect to database - postgres:5432
The tool behavior being executed is onboard
run.sh - [INFO]: 2021-10-25_13:55:26 - Starting the onboard behavior
run.sh - [INFO]: 2021-10-25_13:55:26 - Activating Network Path Connection...
run.sh - [INFO]: 2021-10-25_13:55:26 - [NETWORK_PATH_CHECK] - FAILURE - Unable to connect to database - postgres:5432
The tool behavior being executed is onboard
run.sh - [INFO]: 2021-10-25_13:55:27 - Starting the onboard behavior
run.sh - [INFO]: 2021-10-25_13:55:27 - Activating Network Path Connection...
run.sh - [INFO]: 2021-10-25_13:55:27 - [NETWORK_PATH_CHECK] - FAILURE - Unable to connect to database - postgres:5432
The tool behavior being executed is onboard
run.sh - [INFO]: 2021-10-25_13:55:29 - Starting the onboard behavior
run.sh - [INFO]: 2021-10-25_13:55:29 - Activating Network Path Connection...
run.sh - [INFO]: 2021-10-25_13:55:29 - [NETWORK_PATH_CHECK] - FAILURE - Unable to connect to database - postgres:5432
The tool behavior being executed is onboard
run.sh - [INFO]: 2021-10-25_13:55:31 - Starting the onboard behavior
run.sh - [INFO]: 2021-10-25_13:55:31 - Activating Network Path Connection...
run.sh - [INFO]: 2021-10-25_13:55:31 - [NETWORK_PATH_CHECK] - FAILURE - Unable to connect to database - postgres:5432
The tool behavior being executed is onboard
run.sh - [INFO]: 2021-10-25_13:55:35 - Starting the onboard behavior
run.sh - [INFO]: 2021-10-25_13:55:35 - Activating Network Path Connection...
run.sh - [INFO]: 2021-10-25_13:55:35 - [NETWORK_PATH_CHECK] - SUCCESS - Connected to the database - postgres:5432
run.sh - [INFO]: 2021-10-25_13:55:35 - creating the schema
+ tee /opt/schematool/workarea/out.log
```

**Comment by ayselafsar** [comment]
> I can not reproduce this. What the content of your docker-compose.yaml?

I have not changed anything in your branch, just run it as is.

> Actually, I probably know what happened on your side. When you start up postgres for the first time, it will take a bit longer and in this case the fhir-schematool will fail to run, but not retry anymore, due to the restart policy 'no'. I now changed that to 'on-failure', so that docker will automatically restart the schematool container, until it quits without an error.

That sounds good. I will give it another try.

**Review by ayselafsar — APPROVED** [review]
Works great, thanks, @makuser

**Pull request merged**
